services:
  backend:
    container_name: "devnews"
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - database
    networks:
      - devnews_network

  database:
    image: mysql:8.0
    container_name: "devnews-database"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devnews
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - devnews_db_volume:/var/lib/mysql
    networks:
      - devnews_network

networks:
  devnews_network:

volumes:
  devnews_db_volume:
